age=40
height=5.9
name="Ashu"
is_learning=True
print(type(age))
print(type(height))
print(type(name))
print(type(is_learning))
a=10
b=3
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)
print(a**b)
print(f"My name is {name} and I'm {age} years old and my height is {height}")
age="40"
print(type(age))
age=int(age)
print(type(age))
number=10
decimal_number=float(number)
text_number=str(number)
print(number)
print(decimal_number)
print(text_number)

name="Ashu"
age=40
current_year=2026
approx_birth_year=current_year-age
age_in_5=age+5
age_in_10=age+10
print(name)
print(age)
print(current_year)
print(approx_birth_year)
print(age_in_5)
print(age_in_10)
print(type(name))
print(type(age))
print(type(current_year))
print(type(approx_birth_year))
print(type(age_in_5))
print(type(age_in_10))
height=5.9
print(height)
print(type(height))
age_text="38"
age=int(age_text)
print(age_text)
print(age)
print(type(age_text))
print(type(age))


